### ISSUE TITLE
Jitpack 

### ISSUE THREAD

**Issue by rkmaxwell** [mahdiasd/BottomDialogFilePicker#1]
jitpack is not downloading the dependency to be used on the gradle

**Comment by mahdiasd** [comment]
> jitpack is not downloading the dependency to be used on the gradle

Can you give me more information about the error?
I have no problem downloading it

**Comment by rkmaxwell** [comment]
> > jitpack is not downloading the dependency to be used on the gradle
> 
> Can you give me more information about the error? I have no problem downloading it

I think your latest commit removed the readme, i can't reproduce though i can see you have a release, i don't have the downloaded dependency

**Comment by mahdiasd** [comment]
> > > jitpack is not downloading the dependency to be used on the gradle
> > 
> > 
> > Can you give me more information about the error? I have no problem downloading it
> 
> I think your latest commit removed the readme, i can't reproduce though i can see you have a release, i don't have the downloaded dependency

new release is available

please:
Step 1. Add the JitPack repository to your build file
Add it in your root build.gradle at the end of repositories:
maven { url 'https://jitpack.io' }

Step 2. Add the dependency
dependencies {
	        implementation 'com.github.mahdiasd:BottomDialogFilePicker:1.0.4'
	}

I hope your problem is solved.
