### ISSUE TITLE
MANAGE_EXTERNAL_STORAGE should not be requested.

### ISSUE THREAD

**Issue by or-else** [mahdiasd/BottomDialogFilePicker#3]
Your widget requests and uses `MANAGE_EXTERNAL_STORAGE` (All files access) which makes it unsuitable for most apps. Google Play Store restricts use of `MANAGE_EXTERNAL_STORAGE` to apps which specifically manage storage:

* File managers
* Backup and restore apps
* Anti-virus apps
* Document management apps
* On-device file search
* Disk and file encryption
* Device-to-device data migration

If the app is not in one of the listed categories, it should not request `MANAGE_EXTERNAL_STORAGE` permission. 

Quote from https://developer.android.com/about/versions/11/privacy/storage

*Note: If you publish your app to Google Play, carefully read the [notice](https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play). If you target Android 11 and declare All files access, __it can affect your ability to publish and update your app on Google Play.__*

Quote from https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play

*You should request the MANAGE_EXTERNAL_STORAGE permission only when your app cannot effectively make use of the more privacy-friendly APIs, such as [Storage Access Framework](https://developer.android.com/training/data-storage/shared/documents-files) or the [Media Store API](https://developer.android.com/training/data-storage/shared/media). Additionally, the app's usage of the permission must fall within permitted uses, and must be directly tied to the core functionality of the app.*

**Comment by mahdiasd** [comment]
Hi
Unfortunately, I had mistakenly forgotten to remove the MANAGE_EXTERNAL_STORAGE permission from the manifest
I will definitely remove the permission as soon as possible and pull it on git
Thank you very much for reminding me.

**Comment by mahdiasd** [comment]
Version 1.0.5 was released and the storage permission was removed.
