### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by or-else** [mahdiasd/BottomDialogFilePicker#4]
I'm considering your project to use in https://github.com/tinode/chat
Here are a few things that make it difficult for me to use it:

1. I need camera (CameraX) integration. Telegram's picker has camera as the first tile. Your widget does not. That means I have to create a separate button for camera and if so, I can just use the new [PhotoPicker](https://developer.android.com/training/data-storage/shared/photopicker) from Google. 
2. The [send] button is too much like Telegram and it's not actually sending anything, it's a [done] button, not [send]. Please consider using a more neutral icon, like a checkmark or text [DONE], or make the icon replaceable.
3. Please use standard material design icon for search or make it replaceable.
4. Please consider adding an option to remove circular colored background under icons. Otherwise styling is too much like Telegram.
5. Please consider moving all hardcoded dimension values to Theme, like this:
https://github.com/mahdiasd/BottomDialogFilePicker/blob/master/FilePicker/src/main/res/layout/item_file_picker.xml#L59
7. If mode is single-selection, then there should be an option to just pick on the first click. I.e. not click on image to select, then click [done], but the first click immediately selects the image/video and returns it to the app. In such a case  the selection checkmarks on the image tiles are not needed.
8. There is a visual bug in the UI:
<img width="382" alt="Screenshot 2023-01-05 at 09 17 42" src="https://user-images.githubusercontent.com/5938143/210842637-755c4635-2a9b-4129-a3c6-2cfd20847705.png">
The corners are white, not transparent.

Thank you!

**Comment by mahdiasd** [comment]
@or-else
Thank you very much for your very useful suggestions.
Definitely when I have enough time to do these things. I will do them and upload the new version.
Thank you again

**Comment by mahdiasd** [comment]
Added some features you suggested.
If possible, I will add the others.
At the same time, you can work on the project exclusively by forking the project and do the customizations you want.
Thank you for your cooperation
