### ISSUE TITLE
Add Uri to FileModel

### ISSUE THREAD

**Issue by rkmaxwell** [mahdiasd/BottomDialogFilePicker#7]
Thanks again for the library, I was suggesting you add Uri (content URI)  to the FileModel, I have not been able to get URI from File or Path in Android 11, 13

**Comment by mahdiasd** [comment]
Hello. Thank you.
I hope you're doing well.
Sure, why not?
After adding the URI, I'll let you know here.

**Comment by mahdiasd** [comment]
@rkmaxwell 
I added uri list to FilePickerListener interface
Now you access the uri's in selectedFiles function
